name: Lint Markdown and shell

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  super-linter:
    name: Markdown and ShellCheck
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      statuses: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Run Super-Linter
        uses: github/super-linter@ce838ab356d25fc8e83a16fa6d1fc6f583e14e87 # Super-Linter v8.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENABLE_GITHUB_PULL_REQUEST_SUMMARY_COMMENT: false
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_MARKDOWN: true
          VALIDATE_BASH: true
          LINTER_RULES_PATH: .
          MARKDOWN_CONFIG_FILE: .markdownlint.json

  markdown-check-links:
    name: Markdown - checking links
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v7
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: ".markdownlint.json"
